# Generated by Django 5.1.1 on 2024-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('percent_off', models.IntegerField()),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(choices=[(8, 'Eight'), (9, 'Nine'), (10, 'Ten')])),
                ('type', models.IntegerField(choices=[(1, 'Child'), (2, 'Adult'), (3, 'Senior')])),
            ],
        ),
    ]
