# Generated by Django 5.1.1 on 2024-09-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cast', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('reviews', models.TextField()),
                ('picture_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('mpaa_us_rating', models.CharField(max_length=5)),
                ('show_dates_times', models.JSONField()),
            ],
        ),
    ]
