# Generated by Django 5.1.1 on 2024-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_dates_times',
            field=models.TextField(),
        ),
    ]
