# Generated by Django 5.1.1 on 2024-11-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_dates_times',
        ),
        migrations.AddField(
            model_name='movie',
            name='show_dates_times',
            field=models.ManyToManyField(to='movie.showing'),
        ),
    ]
