# Generated by Django 5.1.1 on 2024-11-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_showing_movie_remove_movie_show_dates_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_dates_times',
            field=models.ManyToManyField(related_name='movies', to='movie.showing'),
        ),
    ]
