# Generated by Django 5.1.1 on 2024-11-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_showing_movie_alter_movie_show_dates_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='movie',
        ),
    ]
