# Generated by Django 5.1.1 on 2024-11-15 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_remove_showing_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='show_dates_times',
        ),
        migrations.AddField(
            model_name='showing',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='movie.movie'),
            preserve_default=False,
        ),
    ]
