# Generated by Django 5.1.1 on 2024-11-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_seat_showroom_showroom_showings_alter_showroom_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_for_ticket', to='movie.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(related_name='tickets_in_booking', to='movie.ticket'),
        ),
    ]
