# Generated by Django 5.1.1 on 2024-11-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_ticket_booking_alter_booking_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.seat')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.showing')),
            ],
            options={
                'unique_together': {('seat', 'showing')},
            },
        ),
    ]
