# Generated by Django 5.1.1 on 2024-11-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_seat_showing_alter_seat_showroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='showing',
        ),
        migrations.DeleteModel(
            name='SeatAssignment',
        ),
        migrations.AddField(
            model_name='seat',
            name='showing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.showing'),
            preserve_default=False,
        ),
    ]
