# Generated by Django 5.1.1 on 2024-11-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_ticket_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
    ]
