# Generated by Django 5.1.1 on 2024-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_remove_booking_showtime_remove_booking_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(to='movie.ticket'),
        ),
    ]
