# Generated by Django 5.1.1 on 2024-12-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_remove_ticket_booking_booking_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
