# Generated by Django 5.1.1 on 2024-12-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
