# Generated by Django 5.1.1 on 2024-12-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_ticket_isbooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
