# Generated by Django 5.1.1 on 2024-10-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='card_cvv2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='appuser',
            name='card_cvv3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='appuser',
            name='card_exp_date2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='appuser',
            name='card_exp_date3',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='appuser',
            name='card_number2',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='appuser',
            name='card_number3',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='appuser',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
    ]
