# Generated by Django 5.1.1 on 2024-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_card_cvv2_appuser_card_cvv3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bookings',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
