# Generated by Django 5.1.1 on 2024-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_booking_date_time_booking_dateplaced_and_more'),
        ('user_api', '0004_alter_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='movie.booking'),
        ),
    ]
